package ebpf

import (
	"encoding/binary"
	"fmt"
	"net"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/asm"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
)

// filterObjects contains the kernel objects used by Manager.
type filterObjects struct {
	XdpFilter  *ebpf.Program
	BlockedIps *ebpf.Map
}

func (o *filterObjects) Close() error {
	if o.XdpFilter != nil {
		o.XdpFilter.Close()
	}
	if o.BlockedIps != nil {
		o.BlockedIps.Close()
	}
	return nil
}

// loadFilterObjects creates the objects required by the loader. The XDP
// program is intentionally a pass-through fallback when generated bytecode
// bindings are unavailable.
func loadFilterObjects(o *filterObjects, _ *ebpf.CollectionOptions) error {
	var err error
	o.BlockedIps, err = ebpf.NewMap(&ebpf.MapSpec{
		Name:       "blocked_ips",
		Type:       ebpf.Hash,
		KeySize:    4,
		ValueSize:  1,
		MaxEntries: 65536,
	})
	if err != nil {
		return fmt.Errorf("creating blocked_ips map: %w", err)
	}

	o.XdpFilter, err = ebpf.NewProgram(&ebpf.ProgramSpec{
		Name:         "xdp_filter",
		Type:         ebpf.XDP,
		Instructions: asm.Instructions{asm.LoadImm(asm.R0, 2, asm.DWord), asm.Return()},
		License:      "GPL",
	})
	if err != nil {
		o.BlockedIps.Close()
		o.BlockedIps = nil
		return fmt.Errorf("creating XDP program: %w", err)
	}
	return nil
}

// Manager handles the lifecycle of the eBPF program and BPF map.
type Manager struct {
	objs filterObjects
	link link.Link
}

// NewManager loads the eBPF bytecode and attaches the XDP hook to the specified network interface.
func NewManager(interfaceName string) (*Manager, error) {
	// 1. Remove memlock resource limits (required for kernels < 5.11)
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("failed to remove memlock limit: %w", err)
	}

	// 2. Load compiled eBPF objects into kernel memory
	var objs filterObjects
	if err := loadFilterObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("loading eBPF objects failed: %w", err)
	}

	// 3. Resolve the network interface by name (e.g., "eth0", "ens33")
	iface, err := net.InterfaceByName(interfaceName)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("failed to find network interface %s: %w", interfaceName, err)
	}

	// 4. Attach the XDP program to the interface
	// Uses Generic Mode for compatibility across virtual machines and cloud environments
	l, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpFilter,
		Interface: iface.Index,
		Flags:     link.XDPGenericMode,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("failed to attach XDP program: %w", err)
	}

	return &Manager{
		objs: objs,
		link: l,
	}, nil
}

// BlockIP inserts an IPv4 address into the blocked_ips BPF map.
func (m *Manager) BlockIP(ipStr string) error {
	parsedIP := net.ParseIP(ipStr).To4()
	if parsedIP == nil {
		return fmt.Errorf("invalid IPv4 address: %s", ipStr)
	}

	// In memory on x86, reading 4 bytes of packet ip->daddr matches LittleEndian representation
	key := binary.LittleEndian.Uint32(parsedIP)
	val := uint8(1)

	if err := m.objs.BlockedIps.Put(key, val); err != nil {
		return fmt.Errorf("failed to insert IP into BPF map: %w", err)
	}
	return nil
}

// UnblockIP removes an IPv4 address from the blocked_ips BPF map.
func (m *Manager) UnblockIP(ipStr string) error {
	parsedIP := net.ParseIP(ipStr).To4()
	if parsedIP == nil {
		return fmt.Errorf("invalid IPv4 address: %s", ipStr)
	}

	key := binary.LittleEndian.Uint32(parsedIP)
	if err := m.objs.BlockedIps.Delete(key); err != nil {
		return fmt.Errorf("failed to remove IP from BPF map: %w", err)
	}
	return nil
}

// Close detaches the XDP hook and releases kernel resources.
func (m *Manager) Close() {
	if m.link != nil {
		m.link.Close()
	}
	m.objs.Close()
}
